### ISSUE TITLE
Forecast issue

### ISSUE THREAD

**Issue by fabaff** [csparpa/pyowm#114] opened 2016-07-06 06:42 UTC
We have integrated pyowm into [Home Assistant](https://home-assistant.io/) a while back and a user reported an [issue](https://github.com/home-assistant/home-assistant/issues/2452) with the forecast.

I see the same traceback if I try to get the forecast directly.

```python
import pyowm

owm = pyowm.OWM('API key')
print(owm.three_hours_forecast_at_coords(43.321, 7.123))
```

```bash
Traceback (most recent call last):
  File "openweather.py", line 5, in <module>
    print(owm.three_hours_forecast_at_coords('46.9614545', '7.4573598'))
  File "/home/fab/Documents/repos/home-assistant/lib64/python3.4/site-packages/pyowm/webapi25/owm25.py", line 424, in three_hours_forecast_at_coords
    assert type(lon) is float or type(lon) is int, "'lon' must be a float"
AssertionError: 'lon' must be a float
(home-assistant) [fab@laptop019 home-assistant]$ python3 openweather.py 
Traceback (most recent call last):
  File "openweather.py", line 5, in <module>
    print(owm.three_hours_forecast_at_coords(46.9614545, 7.4573598))
  File "/testing/lib64/python3.4/site-packages/pyowm/webapi25/owm25.py", line 432, in three_hours_forecast_at_coords
    forecast = self._parsers['forecast'].parse_JSON(json_data)
  File "/testing/lib64/python3.4/site-packages/pyowm/webapi25/forecastparser.py", line 66, in parse_JSON
    for item in d['list']]
  File "/testing/lib64/python3.4/site-packages/pyowm/webapi25/forecastparser.py", line 66, in <listcomp>
    for item in d['list']]
  File "/testing/lib64/python3.4/site-packages/pyowm/webapi25/weather.py", line 462, in weather_from_dictionary
    wind = d['wind'].copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by csparpa** [comment] 2016-07-06 07:21
Hello @fabaff this issue is directly related to #111 

I've just reopened it other users are reporting this issue - unfortunately the API is sending back empty wind data but PyOWM cannot handle such a situation

As this now looks like a major issue, I will release a bugfix tonight... stay tuned!

**Comment by fabaff** [comment] 2016-07-06 07:28
Thanks for the quick response. Sorry, for the duplicate of #111.

**Comment by csparpa** [comment] 2016-07-06 18:42
Fixed with f5c52c31242c0bb469c325324299882139bb561a

I will issue a new release as soon as I can, in the meantime @fabaff can you pls checkout the `dev` branch and check if the issue is gone? Thanks

**Comment by csparpa** [comment] 2016-07-06 21:03
Releasing...

**Closed by csparpa** 2016-07-06 21:03 UTC
Labels: bug

**Comment by fabaff** [comment] 2016-07-06 21:33
Seems to work. Thanks for the new release.
