### ISSUE TITLE
http error

### ISSUE THREAD

**Issue by mateuszdrwal** [csparpa/pyowm#102] opened 2016-03-15 09:34 UTC
i am having problems with this api, it throws an error message whenever i do anything that needs the location string. at first i thought it was something i caused but then to make sure i ran the first example script in the readme and it threw the same error.

`Traceback (most recent call last):
  File "/home/pi/Desktop/programs/text.py", line 9, in <module>
    forecast = owm.daily_forecast("Milan,it")
  File "/usr/local/lib/python2.7/dist-packages/pyowm-2.3.0-py2.7.egg/pyowm/webapi25/owm25.py", line 496, in daily_forecast
    json_data = self._httpclient.call_API(DAILY_FORECAST_URL, params)
  File "/usr/local/lib/python2.7/dist-packages/pyowm-2.3.0-py2.7.egg/pyowm/commons/owmhttpclient.py", line 74, in call_API
    raise api_call_error.APICallError(str(e), e)
APICallError: Exception in calling OWM web API.
Reason: HTTP Error 401: Unauthorized
Caused by: HTTP Error 401: Unauthorized`

i am running Raspbian(a variant of debian linux) on my Raspberry pi 3. i am using python 2.7.9 also, i have tried running the program as root but that does not help.

thanks for any help!

**Comment by csparpa** [comment] 2016-03-17 15:20
Thanks for reporting @mateuszdrwal 

It's not your fault or library's, it's the OWM API that changed.

It looks like OWM changed its v2.5 API forcing the usage of the appid parameter (which carries the API_key)
That's super-bad practice, as it breaks compatibility with existing clients --> which is our case :-S they should have issued a new API version instead.

Eg:

```
# This works
http://api.openweathermap.org/data/2.5/weather?q=London,uk&appid=b1b15e88fa797225412429c1c50c122a  

 # This does not work (HTTP 401 - Unauthorized)
http://api.openweathermap.org/data/2.5/weather?q=London,uk
```

Anyway, I will patch the code as soon as I can, but if anyone wants to help out it would be fantastic - thanks!

**Comment by csparpa** [comment] 2016-03-18 09:57
Possibly fixed by #103 but please @mateuszdrwal if you or any other user find any API error please notify, thanks

**Comment by csparpa** [comment] 2016-03-18 09:58
I will release a new version in a few minutes

**Closed by csparpa** 2016-03-18 09:57 UTC
Labels: bug

**Comment by Harish515** [comment] 2016-08-04 05:38
Below code throwing an error 
pyowm.exceptions.api_call_error.APICallError: Exception in calling OWM web API.
Reason: HTTP Error 401: Unauthorized
Caused by: HTTP Error 401: Unauthorized
Can you please help me?
##### program###########3
import pyowm
import pdb
from pyowm import timeutils
import datetime
now = datetime.datetime.now()
fivedays = datetime.timedelta(days=5)
oneday = datetime.timedelta(days=1)


owm = pyowm.OWM('my_key')  # You MUST provide a valid API key

# Search for current weather in London (UK)
observation = owm.weather_history_at_place('London,uk',start = now-oneday,end=now+fivedays)
print observation

**Comment by csparpa** [comment] 2016-08-04 05:46
A few checks:

 - Did you update PyOWM to the latest version?
  - Is your API key valid? If so, can you pls try to invoke other pyowm methods (eg: weather at coordinates) using your API key?

Please let me know
